name: Diff Tour link
description: Generate a link to the Diff Tour based on a PR.

runs:
  using: composite
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      with:
        script: |
          const script = require(`${{ github.action_path }}/generateTourLink.cjs`)
          const result = await script({ github, context })
          console.log(result)
